# This file was generated by Johny Appleseed
import sqlalchemy as sa

authors = sa.Table(
    metadata,
    id=sa.Integer(primary_key=True),
    # Full name of the author
    name=sa.Text(),
    created_at=sa.DateTime(),
    updated_at=sa.DateTime(),
    archived_at=sa.DateTime(nullable=True),
)

# A post for users to see
posts = sa.Table(
    metadata,
    id=sa.Integer(primary_key=True),
    title=sa.Text(),
    body=sa.Text(),
    created_at=sa.DateTime(),
    updated_at=sa.DateTime(),
    archived_at=sa.DateTime(nullable=True),
)

tags = sa.Table(
    metadata,
    id=sa.Integer(primary_key=True),
    label=sa.Text(),
    created_at=sa.DateTime(),
    updated_at=sa.DateTime(),
    archived_at=sa.DateTime(nullable=True),
)