# This file was generated by Johny Appleseed
# Date: {now}import sqlalchemy as sa


posts = sa.Table(metadata,
    id=sa.Integer(),
    title=sa.Text(),
    body=sa.Text(),
    created_at=sa.DateTime(),
    updated_at=sa.DateTime(),
)


authors = sa.Table(metadata,
    id=sa.Integer(),
    name=sa.Text(),
    created_at=sa.DateTime(),
    updated_at=sa.DateTime(),
)


tags = sa.Table(metadata,
    id=sa.Integer(),
    label=sa.Text(),
    created_at=sa.DateTime(),
    updated_at=sa.DateTime(),
)


